### ISSUE TITLE
Puma does not wait for the old instance to stop before starting new one [Only puma:restart command]

### ISSUE THREAD

**Issue by 907th** [sandelius/mina-puma#8]
Deploy log for [puma:restart] command:

```
-----> Launching
       Command stop sent success
       [4827] Puma        /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/binder.rb:271:in `add_unix_list
ener': There is already a server bound to: /home/webadmin/www/shared/tmp/sockets/puma.sock (RuntimeError)starting in 
cl       from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/binder.rb:119:in `block in parse'u
ster       from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/binder.rb:82:in `each' 
mode..       from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/binder.rb:82:in `parse'
       from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/cluster.rb:280:in `run'       [4827] Puma sta
rting in cluster mode...

       [4       from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/cli.rb:499:in `run'8
27]        from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma:10:in `<top (required)>'*
 Vers       from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/bin/puma:23:in `load'
ion        from /home/webadmin/www/releases/28/vendor/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
       [4827] * Version 2.9.0 (ruby 2.1.2-p95), codename: Team High Five
       [4827] * Min threads: 1, max threads: 16
       [4827] * Environment: production
       [4827] * Process workers: 1
       [4827] * Phased restart available
       [4827] * Listening on unix:///home/webadmin/www/shared/tmp/sockets/puma.sock
 !     ERROR: Deploy failed.

```

May be it is because I'm using Puma in cluster mode.

**Comment by sandelius** [comment]
This might have something to do with it :)

Note that preload_app can’t be used with phased restart, since phased restart kills and restarts workers one-by-one, and preload_app is all about copying the code of master into the workers.

**Comment by sandelius** [comment]
@907th Are you using `preload_app` ??

**Comment by 907th** [comment]
@sandelius Sorry, I can not answer because I'm not using Puma at the moment.
